use my_first_db
db.createCollection('students')
db.students.insert({name:"Bubba", home_state:"IL", lucky_number:12, birthday:{month:01, day:24, year: 1987}})
db.students.insert({name:"Toby", home_state:"GA", lucky_number:25, birthday:{month:06, day:13, year:1998}})
db.students.insert({name:"Hayley", home_state:"NY", lucky_number:455, birthday:{month:11, day:03, year:1888}})
db.students.insert({name:"Sam", home_state:"MI", lucky_number:4, birthday:{month:08, day:10, year:2000}})
db.students.insert({name:"Lana", home_state:"CA", lucky_number:56, birthday:{month:12, day:07, year:1978}})
db.students.find()
db.students.find({home_state: "CA"})
db.students.find({home_state: "WA"})
db.students.find({lucky_number:{$gt: 3}})
db.students.find({lucky_number:{$lte:10}})
db.students.find({lucky_number:{$gte:1, $lte:9}})
db.students.update({}, { $set: { "interests": ['coding', 'brunch', 'MongoDB'] } }, false, true)
db.students.update({name:"Bubba"}, {$push: {interests: 'snowboarding'}})
db.students.update({name:"Toby"}, {$push: {interests: 'tickling'}})
db.students.update({name:"Hayley"}, {$push: {interests: 'fishing'}})
db.students.update({name:"Sam"}, {$push: {interests: 'singing'}})
db.students.update({name:"Lana"}, {$push: {interests: 'standing'}})
db.students.update({name:"Lana"}, {$push: {interests: 'taxes'}})
db.students.update({name:"Lana"}, {$pull: {interests: 'taxes'}})
db.students.remove({home_state:"CA"})
db.students.remove({name:"Sam"})
db.students.deleteOne({lucky_number:{$gt:5}})
db.students.update({}, { $set: { "number_of_belts": 0 } }, false, true)
db.students.update({home_state:"GA"}, { $set: {number_of_belts: 1}}, true)
db.students.update({}, { $rename: { "number_of_belts": "belts_earned" } }, false, true)
db.students.update({}, {$unset: {lucky_number: ""}}, false, true)
db.students.update({}, { $set: { "updated_on": Date() } }, false, true)